basePath: /
host: 'localhost:8080'
info:
  contact: {}
  description: Api Documentation
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
  termsOfService: 'urn:tos'
  title: Api Documentation
  version: '1.0'
paths:
  /hello:
    get:
      consumes:
        - application/json
      operationId: getUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: get
      tags:
        - hello-controller
swagger: '2.0'
tags:
  - description: Hello Controller
    name: hello-controller
